#!/bin/sh
# 
# Greensounds project
# version management tool
#

if [ $# -ne 1 ]
then
	echo "usage: version version_num"
	echo "       version_num format: n.n"
	exit 1
fi


ROOT=.
VERSION=$1

function toNum {
	echo $1 | sed 's/\.//' | sed 's/^0*//'
}

echo "moving version number to $VERSION"

LPRO=$ROOT/build/Greensounds.pro
echo " updating $LPRO"
sed "s/^VERSION = ..*/VERSION = $VERSION/" $LPRO > TMP$$
mv -f TMP$$ $LPRO

PKG=$ROOT/package/Makefile
echo " updating $PKG"
sed "s/\(VERSION := \)[0-9]*\.[0-9]*/\1$VERSION/" $PKG > TMP$$
mv -f TMP$$ $PKG

echo "==> change manually AndroiManifest and SensorAppl.cpp"
open -t rsrc/AndroidManifest.xml src/SensorAppl.cpp

exit 0
